import "./globals.css";
import "./custom.scss";

export const metadata = {
  title: "Library Management system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}




